logger:
  level: DEBUG
  logs:
    esp32_ble_tracker: ERROR 

esphome:
  name: esp-redodo-bms

external_components:
  - source:
      type: local
      path: external_components

esp32:
  board: esp32dev
  framework:
    type: arduino
    advanced:
      minimum_chip_revision: "3.1"

wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
  power_save_mode: NONE
  manual_ip:
    static_ip: !secret wifi_manual_ip
    gateway: !secret wifi_gateway
    subnet: 255.255.255.0

api:
ota:
  - platform: esphome

esp32_ble_tracker:

ble_client:
  - mac_address: !secret ble_client_mac_address
    id: redodo_bms

button:
  - platform: template
    name: "Redodo Force Update"
    icon: "mdi:refresh"
    on_press:
      - lambda: |-
          id(my_bms).update();
          ESP_LOGI("custom", "Forced BMS update requested");

  - platform: restart
    name: "Redodo Monitor ESP32 Restart"
    icon: "mdi:restart"
    
jbd_bms_ble:
  id: my_bms
  ble_client_id: redodo_bms
  update_interval: 15s

sensor:
  - platform: template
    name: "Redodo Power"
    id: redodo_power
    unit_of_measurement: W
    update_interval: 5s
    lambda: 'return id(redodo_voltage).state * id(redodo_current).state;'

  - platform: jbd_bms_ble
    voltage:
      id: redodo_voltage
      name: "Redodo Total Voltage"
      filters:
        - throttle: 5s
    current:
      id: redodo_current
      name: "Redodo Current"
      filters:
        - throttle: 5s
    cell_temperature:
      name: "Redodo Cell Temp"
      filters:
        - throttle: 5s
    mosfet_temperature:
      name: "Redodo Mosfet Temp"
      filters:
        - throttle: 5s
    soc:
      name: "Redodo SOC"
      filters:
        - throttle: 5s
    soh:
      name: "Redodo SOH"
      filters:
        - throttle: 5s
    cycles:
      name: "Redodo Cycles"
      filters:
        - throttle: 5s
    equilibriumstate:
      name: "Redodo Equilibrium State"
      filters:
        - throttle: 5s
    batterystate:
      name: "Redodo Battery State"
      filters:
        - throttle: 5s
    charge:
      name: "Redodo Charge Ah"
      filters:
        - throttle: 5s
    capacity:
      name: "Redodo Capacity Ah"
      filters:
        - throttle: 5s
    cells:
      - name: "Redodo Cell 1 Voltage"
        filters:
          - throttle: 5s
      - name: "Redodo Cell 2 Voltage"
        filters:
          - throttle: 5s
      - name: "Redodo Cell 3 Voltage"
        filters:
          - throttle: 5s
      - name: "Redodo Cell 4 Voltage"
        filters:
          - throttle: 5s
      - name: "Redodo Cell 5 Voltage"
        filters:
          - throttle: 5s
      - name: "Redodo Cell 6 Voltage"
        filters:
          - throttle: 5s
      - name: "Redodo Cell 7 Voltage"
        filters:
          - throttle: 5s
      - name: "Redodo Cell 8 Voltage"
        filters:
          - throttle: 5s

web_server:
  port: 80

#dashboard_import:
#  package_import_url: https://github.com/va13ak/esp_redodo_bms

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "Redodo Monitor IP"